package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/viper"
)

// Config holds all application configuration.
type Config struct {
	LLMProvider   string `mapstructure:"llm_provider"`
	EmbedProvider string `mapstructure:"embed_provider"`
	SSHPort       int    `mapstructure:"ssh_port"`
	HTTPPort      int    `mapstructure:"http_port"`
	WebPassword   string `mapstructure:"web_password"`
	JWTSecret     string `mapstructure:"jwt_secret"`
	DBPath        string `mapstructure:"db_path"`
}

// defaults used by Init and Load when keys are absent.
var defaults = map[string]any{
	"llm_provider":   "anthropic",
	"embed_provider": "ollama",
	"ssh_port":       2222,
	"http_port":      8080,
	"web_password":   "changeme",
	"jwt_secret":     "",
	"db_path":        "~/.hatch/hatch.db",
}

// Load reads config from ~/.hatch/config.yaml and env vars, returns a Config.
func Load() (*Config, error) {
	v := viper.New()

	for k, val := range defaults {
		v.SetDefault(k, val)
	}

	v.SetConfigName("config")
	v.SetConfigType("yaml")
	v.AddConfigPath(configDir())

	v.SetEnvPrefix("HATCH")
	v.SetEnvKeyReplacer(strings.NewReplacer(".", "_"))
	v.AutomaticEnv()

	// Not found is fine — env vars + defaults suffice.
	if err := v.ReadInConfig(); err != nil {
		if _, ok := err.(viper.ConfigFileNotFoundError); !ok {
			return nil, fmt.Errorf("config: read: %w", err)
		}
	}

	var cfg Config
	if err := v.Unmarshal(&cfg); err != nil {
		return nil, fmt.Errorf("config: unmarshal: %w", err)
	}
	return &cfg, nil
}

// knownLLMProviders and knownEmbedProviders list accepted provider values.
var knownLLMProviders = map[string]bool{"anthropic": true, "openai": true, "ollama": true}
var knownEmbedProviders = map[string]bool{"openai": true, "ollama": true}

// Validate returns an error if any config value is out of range or unrecognised.
// Call after Load to catch misconfigured environments at startup.
func (c *Config) Validate() error {
	if !knownLLMProviders[c.LLMProvider] {
		return fmt.Errorf("config: unknown llm_provider %q (want: anthropic, openai, ollama)", c.LLMProvider)
	}
	if !knownEmbedProviders[c.EmbedProvider] {
		return fmt.Errorf("config: unknown embed_provider %q (want: openai, ollama)", c.EmbedProvider)
	}
	if c.SSHPort < 1 || c.SSHPort > 65535 {
		return fmt.Errorf("config: ssh_port %d out of range [1, 65535]", c.SSHPort)
	}
	if c.HTTPPort < 1 || c.HTTPPort > 65535 {
		return fmt.Errorf("config: http_port %d out of range [1, 65535]", c.HTTPPort)
	}
	return nil
}

// Init writes a default config.yaml to ~/.hatch/ if one does not exist.
func Init() error {
	dir := configDir()
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("config init: mkdir %s: %w", dir, err)
	}

	path := filepath.Join(dir, "config.yaml")
	_, statErr := os.Stat(path)
	if statErr == nil {
		fmt.Printf("config already exists: %s\n", path)
		return nil
	}

	content := `# hatch configuration
# Generated by: hatch config init
# Override any value with the HATCH_<KEY> environment variable.

llm_provider: anthropic
embed_provider: ollama
ssh_port: 2222
http_port: 8080
web_password: changeme
jwt_secret: ""
db_path: ~/.hatch/hatch.db
`
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return fmt.Errorf("config init: write %s: %w", path, err)
	}
	fmt.Printf("config written: %s\n", path)
	return nil
}

func configDir() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".hatch")
}
